= TAP(8)
:doctype: manpage
:hardbreaks:
:manmanual: Tap manual
:mansource: TAP {pkgver}

== NAME
tap - MPR in your pocket

== SYNOPSIS
*sudo tap install* [_package_]
*sudo tap remove* [_package_]
*tap search* _search-query_
*sudo tap autoremove*
*sudo tap update*
*sudo tap upgrade*

== CONFIGURATION
*Tap* contains a configuration file at _/etc/tap.cfg_ which is modelled after the options for each command.

Items should generally be self-explanable after viewing the options under the help menu for each command (which are viewable via *tap* _command_ *--help*).

== DESCRIPTION
*Tap* is a feature-rich MPR helper that aims to be a drop-in replacement for *APT*(8). *Tap* provides access to almost every command accessible by *apt*, with MPR functionality integrated directly into said commands.

*install* _package_ ...::
Installs the specified packages onto the system.
+
If any specified packages are available from multiple sources, *Tap* will prompt the user to choose which source to install from and then will proceed with the transaction.

*remove* _package_ ...::
Removes the specified packages from the system.
+
If removing any of the specified packages would cause an essential (*dpkg*(1)) package to be removed, *Tap* aborts the transaction.

*search* _query params_ ...::
Searches the AUR and MPR for each of the specified query parameters.

*autoremove*::
Removes any packages that are no longer needed by a package on the system.

*update*::
Updates the APT and MPR repository caches on the local system.

*upgrade*::
Checks if any installed packages have upgrades available for installation.

== BUGS
Issues, as well as feature requests, should be posted on the project's GitHub page: ::
`+https://github.com/hwittenborn/tap+`

A public Matrix room also exists, which is where most communication involving development and general discussion takes place: ::
#tap:hunterwittenborn.com

== AUTHORS
Hunter Wittenborn `+<hunter@hunterwittenborn.com+`

A full list of contributors can be found by running *git shortlog -esn* on Tap’s Git repository (linked under *BUGS*).
