name: Bug report
description: Issues with using Tap, installing packages, resolving dependencies, etc.
labels: ["bug"]
body:
  - type: textarea
    attributes:
      label: Issue
      placeholder: Type a complete description of your issue
    validations:
      required: true
  - type: input
    attributes:
      label: Tap version
      placeholder: tap --version
    validations:
      required: true
