def help_menu(application_name, application_version):
	print(f"{application_name} ({application_version}) - MPR in your pocket")
	print()
	print(f"Usage: {application_name} [command] [packages/options]")
	print()
	print("Commands:")
	print("  install                 Install packages")
	print("  update/upgrade          Update packages")
	print("  search                  Search for packages")
	print("  list-packages           List installed packages built from the MPR")
	print()
	print("Options:")
	print("  -h, --help              Bring up this help menu")
	print("  -L, --skip-less-pipe    Don't pipe output from 'list-packages' into 'less' when output is taller than the terminal height")
	print("  -V, --version           Print version information and exit")
